{
 "title": "CISEI data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "city", "label": "City", "query": "Palermo" }
  ]
 },
 "panels": [
  {
   "title": "Gender $city",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (\n        SELECT\n            COUNT(*)\n        FROM\n            person_info\n        WHERE (details ->> 'Sesso' = 'F'\n            OR details ->> 'Sesso' = 'FEMMINILE')\n        AND (LENGTH('${city:raw}') = 0\n            OR details ->> 'Luogo di nascita' ILIKE '%${city:raw}%'\n            OR details ->> 'Congiugimento (città)' ILIKE '%${city:raw}%'\n            OR details ->> 'Provenienza' ILIKE '%${city:raw}%'\n            OR details ->> 'Città di provenienza' ILIKE '%${city:raw}%'\n            OR details ->> 'Provincia' ILIKE '%${city:raw}%'\n            --OR details ->> 'Provincia' ILIKE '%${city_code:raw}%'\n            OR details ->> 'Luogo di nascita / patria / nazione' ILIKE '%${city:raw}%'\n            OR details ->> 'Luogo di nascita normalizzato' ILIKE '%${city:raw}%')) AS women,\n(\n    SELECT\n        COUNT(*)\n    FROM\n        person_info\n    WHERE (details ->> 'Sesso' = 'M'\n        OR details ->> 'Sesso' = 'MASCHILE')\n    AND (LENGTH('${city:raw}') = 0\n        OR details ->> 'Luogo di nascita' ILIKE '%${city:raw}%'\n        OR details ->> 'Congiugimento (città)' ILIKE '%${city:raw}%'\n        OR details ->> 'Provenienza' ILIKE '%${city:raw}%'\n        OR details ->> 'Città di provenienza' ILIKE '%${city:raw}%'\n        OR details ->> 'Provincia' ILIKE '%${city:raw}%'\n        --OR details ->> 'Provincia' ILIKE '%${city_code:raw}%'\n        OR details ->> 'Luogo di nascita / patria / nazione' ILIKE '%${city:raw}%'\n        OR details ->> 'Luogo di nascita normalizzato' ILIKE '%${city:raw}%')) AS men,\n(\n    SELECT\n        COUNT(*)\n    FROM\n        person_info\n    WHERE\n        details ->> 'Sesso' IS NULL\n        AND (LENGTH('${city:raw}') = 0\n            OR details ->> 'Luogo di nascita' ILIKE '%${city:raw}%'\n            OR details ->> 'Congiugimento (città)' ILIKE '%${city:raw}%'\n            OR details ->> 'Provenienza' ILIKE '%${city:raw}%'\n            OR details ->> 'Città di provenienza' ILIKE '%${city:raw}%'\n            OR details ->> 'Provincia' ILIKE '%${city:raw}%'\n            --OR details ->> 'Provincia' ILIKE '%${city_code:raw}%'\n            OR details ->> 'Luogo di nascita / patria / nazione' ILIKE '%${city:raw}%'\n            OR details ->> 'Luogo di nascita normalizzato' ILIKE '%${city:raw}%')) AS unknown\nFROM\n    person_info\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Number of emigrants by year $city",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    EXTRACT(YEAR FROM trip_date)::text AS date,\n    COUNT(*) AS persons\nFROM\n    person_info\nWHERE\n    trip_date IS NOT NULL AND (\n    LENGTH('${city:raw}') = 0\n    OR details ->> 'Luogo di nascita' ILIKE '%${city:raw}%'\n    OR details ->> 'Congiugimento (città)' ILIKE '%${city:raw}%'\n    OR details ->> 'Provenienza' ILIKE '%${city:raw}%'\n    OR details ->> 'Città di provenienza' ILIKE '%${city:raw}%'\n    OR details ->> 'Provincia' ILIKE '%${city:raw}%'\n    --OR details ->> 'Provincia' ILIKE '%${city_code:raw}%'\n    OR details ->> 'Luogo di nascita / patria / nazione' ILIKE '%${city:raw}%'\n    OR details ->> 'Luogo di nascita normalizzato' ILIKE '%${city:raw}%')\nGROUP BY\n    date\nORDER BY\n    date;\n"
    }
   ]
  },
  {
   "title": "Age of departure $city",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n    age::text AS \"Age\",\n    COUNT(*) AS \"Age Count\"\nFROM\n    person_info\nWHERE\n    age < 75\n    AND (LENGTH('${city:raw}') = 0\n        OR details ->> 'Luogo di nascita' ILIKE '%${city:raw}%'\n        OR details ->> 'Congiugimento (città)' ILIKE '%${city:raw}%'\n        OR details ->> 'Provenienza' ILIKE '%${city:raw}%'\n        OR details ->> 'Città di provenienza' ILIKE '%${city:raw}%'\n        OR details ->> 'Provincia' ILIKE '%${city:raw}%'\n        --OR details ->> 'Provincia' ILIKE '%${city_code:raw}%'\n        OR details ->> 'Luogo di nascita / patria / nazione' ILIKE '%${city:raw}%'\n        OR details ->> 'Luogo di nascita normalizzato' ILIKE '%${city:raw}%')\nGROUP BY\n    age;\n"
    }
   ]
  },
  {
   "title": "People from $city",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    surname AS \"Surname\",\n    full_name AS \"Full_name\",\n    age AS \"Age\",\n    trip_date AS \"Trip date\",\n    registration_place AS \"Registration place\",\n    details AS \"Details\"\nFROM\n    person_info\nWHERE\n    LENGTH('${city:raw}') = 0\n    OR details ->> 'Luogo di nascita' ILIKE '%${city:raw}%'\n    OR details ->> 'Congiugimento (città)' ILIKE '%${city:raw}%'\n    OR details ->> 'Provenienza' ILIKE '%${city:raw}%'\n    OR details ->> 'Città di provenienza' ILIKE '%${city:raw}%'\n    OR details ->> 'Provincia' ILIKE '%${city:raw}%'\n    --OR details ->> 'Provincia' ILIKE '%${city_code:raw}%'\n    OR details ->> 'Luogo di nascita / patria / nazione' ILIKE '%${city:raw}%'\n    OR details ->> 'Luogo di nascita normalizzato' ILIKE '%${city:raw}%'\nLIMIT 10000;\n"
    }
   ]
  }
 ]
}