---
version: "3"
services:
  database_pg:
    image: postgres:13.2
    container_name: database_pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 3

  grafana:
    image: grafana/grafana:9.1.8
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana
    depends_on:
      - database_pg

  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - database_pg

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/default.conf:/etc/nginx/sites-available/default
      # - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    depends_on:
      - grafana

volumes:
  grafana-pg-storage:
    external: true
  grafana-storage:
    external: true
  letsencrypt:
    external: true

#   cisei:
#     image: index.docker.io/framaxwlad/cisei:latest
#     container_name: cisei
#     restart: always
#     depends_on:
#       - database_pg
#     networks:
#       - local_net
