---
version: "3"
services:
  database_pg:
    image: postgres:13.2
    container_name: database_pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 3

  grafana:
    image: grafana/grafana:9.1.8
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    depends_on:
      - database_pg

  nginx:
    image: nginx:1.23.1
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/letsencrypt/live:/etc/letsencrypt/live:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw

#   cisei:
#     image: index.docker.io/framaxwlad/cisei:latest
#     container_name: cisei
#     restart: always
#     depends_on:
#       - database_pg

volumes:
  grafana-pg-storage:
    external: true
  grafana-storage:
    external: true
  letsencrypt:
    external: true
